'use strict';
const config=window.STUDIO_CONFIG;
const t=text=>window.STUDIO_I18N?window.STUDIO_I18N.translate(text):text;
const setStatus=text=>{if(window.STUDIO_I18N)window.STUDIO_I18N.showStatus(text);else document.querySelector('#form-status').textContent=text};
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=value=>{try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)?url.href:''}catch{return ''}};
const projects=document.querySelector('#project-list');
projects.innerHTML=config.PROJECTS.map((p,i)=>{const title=`<p class="project-category">${escapeHTML(p.category)} · CONCEPTO</p><h3>${escapeHTML(p.name)}</h3><p class="project-style">${escapeHTML(p.style)}</p><p class="project-description">${escapeHTML(p.description)}</p>`;const details=`<div class="tags">${p.tags.map(tag=>`<span>${escapeHTML(tag)}</span>`).join('')}</div><a class="text-link" href="${escapeHTML(safeURL(p.url))}" target="_blank" rel="noopener noreferrer" aria-label="Ver proyecto ${escapeHTML(p.name)}; se abre en otra pestaña">Ver proyecto <span aria-hidden="true">↗</span></a>`;return `<article class="project ${[2,4].includes(i)?'full':i%2?'reverse':''}"><a class="project-visual" href="${escapeHTML(safeURL(p.url))}" target="_blank" rel="noopener noreferrer" aria-label="Abrir concepto ${escapeHTML(p.name)} en otra pestaña"><div class="browser"><div class="browser-bar"><span>● ● ●</span><span>${escapeHTML(p.name)} · CONCEPTO WEB</span><span>↗</span></div><img src="assets/projects/${escapeHTML(p.id)}.webp" width="1440" height="1000" loading="lazy" alt="Vista de escritorio del concepto web ${escapeHTML(p.name)}"></div></a><div class="project-info"><span class="project-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><div>${title}</div><div class="project-details">${details}</div></div></article>`}).join('');
document.querySelectorAll('[data-price]').forEach(el=>el.textContent=config.PRICING[el.dataset.price]);
document.querySelector('#year').textContent=new Date().getFullYear();
const header=document.querySelector('#header');const updateHeader=()=>header.classList.toggle('scrolled',window.scrollY>20);updateHeader();window.addEventListener('scroll',updateHeader,{passive:true});
const menu=document.querySelector('#mobile-menu');const toggle=document.querySelector('.menu-toggle');
const closeMenu=()=>menu.close();toggle.addEventListener('click',()=>{menu.showModal();toggle.setAttribute('aria-expanded','true');document.body.classList.add('menu-open')});document.querySelector('.menu-close').addEventListener('click',closeMenu);menu.addEventListener('close',()=>{document.body.classList.remove('menu-open');toggle.setAttribute('aria-expanded','false');toggle.focus()});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{closeMenu();const target=document.querySelector(a.hash);if(target){setTimeout(()=>{target.setAttribute('tabindex','-1');target.focus({preventScroll:true});target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},0)}}));window.addEventListener('resize',()=>{if(innerWidth>800&&menu.open)closeMenu()});
const message='Hola, he visto vuestra web de Studio Web y me gustaría mejorar la página de mi restaurante.';
const whatsapp=config.WHATSAPP_NUMBER.replace(/\D/g,'');
if(whatsapp.length>=8){document.querySelectorAll('.whatsapp-link,.floating-contact').forEach(a=>{a.href=`https://wa.me/${whatsapp}?text=${encodeURIComponent(message)}`;a.target='_blank';a.rel='noopener noreferrer'})}else{document.querySelectorAll('.whatsapp-link').forEach(a=>{a.href='#contact-form';a.addEventListener('click',()=>{setStatus('WhatsApp todavía no está disponible. Puedes preparar tu consulta en este formulario.')})})}
document.querySelectorAll('[data-contact]').forEach(a=>{const key=a.dataset.contact;const value=config[key];if(value){const href=key==='EMAIL'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)?`mailto:${value}`:safeURL(value);if(href){a.href=href;if(key!=='EMAIL'){a.target='_blank';a.rel='noopener noreferrer'}return}}a.addEventListener('click',()=>{setStatus('Este canal todavía no está disponible. Puedes preparar tu consulta aquí.')})});
const form=document.querySelector('#contact-form');const status=document.querySelector('#form-status');const endpoint=safeURL(config.FORM_ENDPOINT);
if(endpoint){document.querySelector('#form-notice').textContent='Utilizaremos los datos que nos facilites para responder a tu consulta.';document.querySelector('#copy-request').hidden=true}
const compose=()=>{const data=new FormData(form);return `${t('Consulta para Studio Web')}\n\n${t('Nombre')}: ${data.get('nombre')}\n${t('Restaurante')}: ${data.get('restaurante')}\n${t('Ciudad')}: ${data.get('ciudad')}\n${t('Teléfono / WhatsApp')}: ${data.get('telefono')}\n${t('Web actual')}: ${t(data.get('web_actual')||'Sin indicar')}\n\n${data.get('mensaje')}`};
form.addEventListener('submit',async event=>{event.preventDefault();if(!endpoint){setStatus('Tu solicitud no se ha enviado: el envío aún no está disponible. Usa «Copiar consulta» para guardar el texto.');return}const button=form.querySelector('[type=submit]');button.disabled=true;setStatus('Enviando tu solicitud…');try{const response=await fetch(endpoint,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Error de envío');setStatus('Tu solicitud se ha enviado. Gracias por contarnos tu idea.');form.reset()}catch{setStatus('No se ha podido enviar la solicitud. Inténtalo de nuevo más tarde.')}finally{button.disabled=false}});
document.querySelector('#copy-request').addEventListener('click',async()=>{if(!form.reportValidity())return;try{await navigator.clipboard.writeText(compose());setStatus('Consulta copiada. Guárdala para enviarla cuando el contacto esté disponible. No se ha enviado ningún dato.')}catch{setStatus('No se ha podido copiar automáticamente. Puedes seleccionar y copiar el texto de los campos. No se ha enviado ningún dato.')}});
document.querySelectorAll('[data-plan]').forEach(a=>a.addEventListener('click',()=>{const field=form.elements.mensaje;if(!field.value.trim())field.value=document.documentElement.lang==='en'?`I’d like information about the ${t(a.dataset.plan)} for my restaurant.`:`Me gustaría recibir información sobre ${a.dataset.plan} para mi restaurante.`}));
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelector('.hero-copy').classList.add('reveal')}
